/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as AnalyticsImport } from './routes/analytics'
import { Route as IndexImport } from './routes/index'
import { Route as AccidentsIndexImport } from './routes/accidents/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AccidentsNewImport } from './routes/accidents/new'
import { Route as AccidentsAccidentIdEditImport } from './routes/accidents/$accidentId/edit'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsRoute = AnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccidentsIndexRoute = AccidentsIndexImport.update({
  id: '/accidents/',
  path: '/accidents/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AccidentsNewRoute = AccidentsNewImport.update({
  id: '/accidents/new',
  path: '/accidents/new',
  getParentRoute: () => rootRoute,
} as any)

const AccidentsAccidentIdEditRoute = AccidentsAccidentIdEditImport.update({
  id: '/accidents/$accidentId/edit',
  path: '/accidents/$accidentId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/accidents/new': {
      id: '/accidents/new'
      path: '/accidents/new'
      fullPath: '/accidents/new'
      preLoaderRoute: typeof AccidentsNewImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/accidents/': {
      id: '/accidents/'
      path: '/accidents'
      fullPath: '/accidents'
      preLoaderRoute: typeof AccidentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/accidents/$accidentId/edit': {
      id: '/accidents/$accidentId/edit'
      path: '/accidents/$accidentId/edit'
      fullPath: '/accidents/$accidentId/edit'
      preLoaderRoute: typeof AccidentsAccidentIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/profile': typeof ProfileRoute
  '/accidents/new': typeof AccidentsNewRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/accidents': typeof AccidentsIndexRoute
  '/accidents/$accidentId/edit': typeof AccidentsAccidentIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/profile': typeof ProfileRoute
  '/accidents/new': typeof AccidentsNewRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/accidents': typeof AccidentsIndexRoute
  '/accidents/$accidentId/edit': typeof AccidentsAccidentIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/profile': typeof ProfileRoute
  '/accidents/new': typeof AccidentsNewRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/accidents/': typeof AccidentsIndexRoute
  '/accidents/$accidentId/edit': typeof AccidentsAccidentIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/profile'
    | '/accidents/new'
    | '/auth/login'
    | '/auth/signup'
    | '/accidents'
    | '/accidents/$accidentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/profile'
    | '/accidents/new'
    | '/auth/login'
    | '/auth/signup'
    | '/accidents'
    | '/accidents/$accidentId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/profile'
    | '/accidents/new'
    | '/auth/login'
    | '/auth/signup'
    | '/accidents/'
    | '/accidents/$accidentId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ProfileRoute: typeof ProfileRoute
  AccidentsNewRoute: typeof AccidentsNewRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AccidentsIndexRoute: typeof AccidentsIndexRoute
  AccidentsAccidentIdEditRoute: typeof AccidentsAccidentIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ProfileRoute: ProfileRoute,
  AccidentsNewRoute: AccidentsNewRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AccidentsIndexRoute: AccidentsIndexRoute,
  AccidentsAccidentIdEditRoute: AccidentsAccidentIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analytics",
        "/profile",
        "/accidents/new",
        "/auth/login",
        "/auth/signup",
        "/accidents/",
        "/accidents/$accidentId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analytics": {
      "filePath": "analytics.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/accidents/new": {
      "filePath": "accidents/new.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/accidents/": {
      "filePath": "accidents/index.tsx"
    },
    "/accidents/$accidentId/edit": {
      "filePath": "accidents/$accidentId/edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
